name: Android APK Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # 깃허브 서버 안에서 app.zip 압축을 자동으로 푸는 명령어입니다.
    - name: Unzip app directory
      run: |
        unzip app.zip -d .
        rm app.zip

    - name: Buildozer Action
      uses: ArtemSanya/buildozer-action@v1
      with:
        command: buildozer android debug
        repository_root: .
